import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/shared/theme-provider";
import Header from "@/components/shared/header";

const tajawal = localFont({
  src: "./fonts/Questv1 Regular.ttf",
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Salwa Chemistry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${tajawal.className} antialiased max-w-xl md:max-w-4xl lg:max-w-6xl mx-auto `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="min-h-screen px-2 sm:px-6 lg:px-8 mx-auto w-full max-w-xl md:max-w-4xl lg:max-w-6xl">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
